# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: AbdoCode.AbdoCode
PackageVersion: 4.0.108
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/code-ksa/abdocode/releases/download/v4.0.108/AbdoCode-4.0.108-x64-setup.exe
  InstallerSha256: 89F5C80920430189E4A8AD291F6CC4BACF8B13543F3017799560757ACF9608A8
ManifestType: installer
ManifestVersion: 1.10.0
